name: CI-lint

on: 
  push: 
  workflow_dispatch:

env:
  LINUX_VERSION: 5.14.0-1036-oem
  PROCESSES: 32

jobs:
  lint:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 1
        - name: setup toolchain
          run: |
            sudo apt-get update > /dev/null
            sudo apt-get install gcc make bear cppcheck -y
        
        # install linux-headers
        - name: install linux-headers
          run: sudo apt-get install -y linux-headers-${{env.LINUX_VERSION}}

        #set SYSSRC due to kernel-open/Makefile line 31 would possibly not find headers to compile against
        - name: build compile database with (bear aka build ear)
          run: bear make modules SYSSRC=/lib/modules/${{env.LINUX_VERSION}}/build -j${{env.PROCESSES}}

        - name: cppcheck
          run: cppcheck --project=compile_commands.json --max-ctu-depth=10 --enable=all --xml 2>report.xml

        - name: convert cppcheck xml to html
          run: |
            sudo apt-get install -y python-pygments
            curl -O https://raw.githubusercontent.com/danmar/cppcheck/main/htmlreport/cppcheck-htmlreport
            python ./cppcheck-htmlreport report.xml
